rename "nEc 01[01] tina tao %%.tiff" "tita.tiff"
rename "nEc 01[02] S tin maj.tiff" "tima.tiff"
rename "nEc 01[03] S tin gut.tiff" "tigu.tiff"
rename "nEc 01[04] S not bon.tiff" "nobo.tiff"
rename "nEc 01[05] not jul.tiff" "noju.tiff"
rename "nEc 01[06] S cry cin.tiff" "crci.tiff"
rename "nEc 01[07] S cryp ber %%.tiff" "crbe.tiff"
rename "nEc 01[08] S cry sou.tiff" "crso.tiff"
rename "nEc 01[09] cry obs.tiff" "crob.tiff"
rename "nEc 01[10] S cry und.tiff" "crun.tiff"
rename "nEc 01[11] S cry var.tiff" "crva.tiff"
rename "nEc 01[12] S cryp bart.tiff" "crba.tiff"
rename "nEc 01[13] e cryp tran.tiff" "crtr.tiff"
rename "nEc 01[14] cryp tata.tiff" "crta.tiff"
rename "nEc 01[15] noth pent.tiff" "nope.tiff"
rename "nEc 01[16] noth curv.tiff" "nocu.tiff"
rename "nEc 02[01] S tac dom.tiff" "tado.tiff"
rename "nEc 02[02] S pod pod.tiff" "popo.tiff"
rename "nEc 02[03] pod occ.tiff" "pooc.tiff"
rename "nEc 03[01] Sphe Sphe humb.tiff" "sphu.tiff"
rename "nEc 04[01] Diom pho irr.tiff" "phir.tiff"
rename "nEc 04[02] tha mel.tiff" "thme.tiff"
rename "nEc 05[01] fulm gla.tiff" "fugl.tiff"
rename "nEc 05[02] dapt cap.tiff" "daca.tiff"
rename "nEc 05[03] pter pha.tiff" "ptph.tiff"
rename "nEc 05[04] proc aeq.tiff" "prae.tiff"
rename "nEc 05[05 proc par.tiff" "prpa.tiff"
rename "nEc 05[06] puff cre.tiff" "pucr.tiff"
rename "nEc 05[07] puff bull.tiff" "pubu.tiff"
rename "nEc 05[08] puff gri.tiff" "pugr.tiff"
rename "nEc 05[09] puff lhe.tiff" "pulh.tiff"
rename "nEc 06[01] oce oce.tiff" "ococ.tiff"
rename "nEc 06[02] oce gra.tiff" "ocgr.tiff"
rename "nEc 06[03] pel mar.tiff" "pema.tiff"
rename "nEc 06[04] oce mic.tiff" "ocmi.tiff"
rename "nEc 06[05] oce teth.tiff" "octe.tiff"
rename "nEc 06[06] oce cas.tiff" "occa.tiff"
rename "nEc 06[07] oce mar.tiff" "ocma.tiff"
rename "nEc 06[08] oce mel.tiff" "ocme.tiff"
rename "nEc 06[09] oce hom.tiff" "ocho.tiff"
rename "nEc 06[10] oce hor.tiff" "ocho.tiff"
rename "nEc 07[01] Pha Phae aeth.tiff" "phae.tiff"
rename "nEc 08[01] fre magn.tiff" "frma.tiff"
rename "nEc 08[02] fre mino.tiff" "frmi.tiff"
rename "nEc 09[01] sou neb.tiff" "sone.tiff"
rename "nEc 09[03] sul gra.tiff" "sugr.tiff"